# site properties and page defaults
title: Dong Lab
subtitle: at Adams Center for Parkinson's Research, Yale School of Medicine, Yale University
description: We use computational genomics methods to study transcriptional regulation and its role in neurological diseases.
logo-text: false
header: images/background.jpg
footer: images/background.jpg
header-dark: true
footer-dark: true


# site social media and other links
links:
  email: xianjun.dong@yale.edu
  orcid: 0000-0002-8052-9320
  google-scholar: 2TIgdeoAAAAJ
  github: TheDongLab
  twitter: sterding

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # # markdown files in /_posts
  # - scope:
  #     type: "posts"
  #   values:
  #     layout: post

collections:
  # generate page for each member
  members:
    output: true
  # # generate page for each post
  # posts:
  #   output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
